### ISSUE TITLE
Support for iPad Pro 9,7"

### ISSUE THREAD

**Issue by GaetanDetilloux** [anthonya1999/GoodNight#100]
Dear,

Tried the goodnight app on the new iPad Pro 9.7" but it doesn't work anymore, maybe something related to the new True Tone display ? I think Goodnight app is still necessary to tune color on screen with color setup since nor Nightshift or True tone are able to do that,

Thank you,

Gaëtan

**Comment by anthonya1999** [comment]
Well actually, on all the iPad Pro models on the newer versions of iOS, IOMobileFramebufferGetMatrix & IOMobileFramebufferSetMatrix seem to just not do anything. It doesn't fail, in fact it returns 0 which means success, it just...quite literally doesn't change anything. I'll have to see what's up with that...

**Comment by GaetanDetilloux** [comment]
Very interesting ! but seems not so easy to fix, I will follow the changes to understand ! Thank you anyway, when it is fixed I will try again on iPad Pro both 9,7 and 12,9

**Comment by anthonya1999** [comment]
I think I'll close this for now, and then if I find a fix, I will certainly push the changes ASAP! Thanks!
