### ISSUE TITLE
App crashing on iOS 9.3.2 Beta 1

### ISSUE THREAD

**Issue by shad0whawk** [anthonya1999/GoodNight#101]
This app has been installed for quite some time now and has worked great on 9.3 and 9.3.1. Now I'm running 9.3.2 Beta 1 and it crashes right after opening. It still shows in the app switcher, and selecting it will cause it to crash again. Has anyone else been having this issue?  Any thoughts on the cause?

**Comment by shad0whawk** [comment]
I should mention that it's been running on an iPhone 6s Plus

**Comment by wasp604** [comment]
Mine and a friend's began crashing recently as well, and I can to longer
sideload it onto new devices, since xcode now has serious issues with it.

**Comment by jasonfish** [comment]
Same here. Started crashing on startup about a week ago on iOS 9.3. Nothing else changed, that I can think of. One night it was working, the next it would just cause my screen to flash for a split second after tapping the icon. Was there an expiration date somewhere? :)

**Comment by greatquux** [comment]
Yep- all "free" Apple ID provisioning profiles only last for 3 months. Then you've got to recompile the app and reinstall it. I forgot the exact steps but it wasn't hard at all, just annoying. The $99 Apple developer ID expires in a year.

Sent from my mobile phone

On Apr 13, 2016, at 1:35 AM, jasonfish <notifications@github.com<mailto:notifications@github.com>> wrote:


Same here. Started crashing on startup about a week ago on iOS 9.3. Nothing else changed, that I can think of. One night it was working, the next it would just cause my screen to flash for a split second after tapping the icon. Was there an expiration date somewhere? :)

**Comment by drz01** [comment]
@shad0whawk On 9.3.2PB2 here, and can confirm the same. The widget seems to still work: specifically the darkroom mode button toggles, though the gamma button changes the labelling only without shift in colour temp.

**Comment by greatquux** [comment]
Has anyone tried recompiling and reinstalling it? The flashing and quitting when launching is the same behaviour I get when my Apple ID provisioning profile has expired and I need to renew it in Xcode and reinstall the app (and it happens with another app I sideload also).

**Comment by wasp604** [comment]
I have tried to, but xcode won't allow it. Keeps getting errors with app
groups and not having permissions to fix the issue. A search online shows
that it's specific to the latest xcode. Have not tried an earlier version
of xcode yet, but others report success.

**Comment by Pukinator** [comment]
It also crashes on 9.2

**Comment by greatquux** [comment]
Yes, the issue https://github.com/anthonya1999/GoodNight/issues/99 documents the issue with Xcode 9.3, and I myself had to use Xcode 9.2.1 first to give my Apple ID the proper permissions. Then I could compile with Xcode 9.3 properly and it worked great.  So I'd recommend trying that first.  You should only have to do it once.

**Comment by drz01** [comment]
Yes I can confirm the current issue only possible *after* bypass of #99 using the established method!

**Comment by anthonya1999** [comment]
Is this okay to mark as closed?

**Comment by drz01** [comment]
I gave up trying. Is it just me then?

**Comment by greatquux** [comment]
Apple has just changed their free provisioning profiles so that they will only work for 7 days now.  It's really ridiculous, but means you must recompile and install every week.

**Comment by drz01** [comment]
I meant not even a fresh compile works -- dark mode toggle only...
