### ISSUE TITLE
Running Xcode 7.2 w/ iOS 9.3.1

### ISSUE THREAD

**Issue by alyssalng** [anthonya1999/GoodNight#105]
I was finally able to fix the group containers entitlements by installing 7.2, but when I tried to install it, I got this message, which says "Could not find Developer Disk image":

![screen shot 2016-05-23 at 1 56 51 am](https://cloud.githubusercontent.com/assets/19526438/15465632/705d6bde-208a-11e6-8c39-401da6f70be0.png)

As I mentioned in the title, I'm using Xcode 7.2 and trying to run Good Night on an iphone 5 iOS 9.3.1

How do I fix this? Any help would be great.

**Comment by tonytien** [comment]
Xcode 7.2 doesn't have the right resources to develop for iOS 9.3+. You'll need to install Xcode 7.3+, which added support for iOS 9.3.

**Comment by anthonya1999** [comment]
Or you should be able to cheat a little, and copy the developer disk image FROM Xcode 7.3 TO Xcode 7.2, if you really want to use 7.3. But for simplicity, I'd just say use Xcode 7.3
