### ISSUE TITLE
Errors during build

### ISSUE THREAD

**Issue by codeman869** [anthonya1999/GoodNight#11]
Are there any special build instructions? I'm having issues building the project on Xcode 7.0.0 beta and 7.1.1. Tried adding the notification center framework to the Build Phases to see if that would resolve it.

https://gist.github.com/codeman869/f785cbdfd70ea6b57009

**Comment by anthonya1999** [comment]
Oh yes, I probably should put this in the README. You cannot build/compile using the iOS Simulator. You must select "Generic iOS Device" or your own device if plugged in when building.

**Comment by anthonya1999** [comment]
I added a notice in the README to avoid any confusion. Thanks!
