### ISSUE TITLE
Push IPA releases

### ISSUE THREAD

**Issue by bigmittens** [anthonya1999/GoodNight#112]
https://github.com/anthonya1999/GoodNight/issues/102#issuecomment-258018599

**Comment by bigmittens** [comment]
Thought this might have ended up unseen since the project was inactive for a while, obviously feel free to close if you aren't interested.

**Comment by anthonya1999** [comment]
Thank you. I'd love to push some IPAs, but due to f.lux's wishes, I really would not like. Thanks for understanding.
