### ISSUE TITLE
Crashes on every menu opening since the widget was added

### ISSUE THREAD

**Issue by timothysee27** [anthonya1999/GoodNight#13]

**Comment by anthonya1999** [comment]
Did you change the middle portion bundle identifier to something different and then change the widget to the same thing? If not, you have to do that first.

**Comment by mariokorte** [comment]
I guess this should be closed. Surely related to incorrect bundle ids.

**Comment by anthonya1999** [comment]
Yeah, was going to close it soon anyway...
