### ISSUE TITLE
Does not seem to support iOS 9.1 on the iPhone 6. It appears low quality, static, and blurry.

### ISSUE THREAD

**Issue by lightzoff** [anthonya1999/GoodNight#14]

**Comment by anthonya1999** [comment]
Yeah, honestly I haven't noticed any problems with the display running on 9.1 (I have a 6 Plus). Can you take a screenshot maybe?

**Comment by deemidroll** [comment]
The same problem with iOS 9.1 on the iPhone 5S: 
![screenshot 1](https://cloud.githubusercontent.com/assets/2768376/11241294/aec59af8-8e0a-11e5-819b-1e4b945dd3de.jpg)
![screenshot 2](https://cloud.githubusercontent.com/assets/2768376/11241293/aec4b002-8e0a-11e5-854b-33dcc1761bc3.jpg)
![screenshot 3](https://cloud.githubusercontent.com/assets/2768376/11241292/aec1e91c-8e0a-11e5-8a0c-b11614a277da.jpg)

**Comment by anthonya1999** [comment]
Hmm, interesting...does it only happen when on certain Kelvin levels? Or is it no matter what the slider is on?

**Comment by deemidroll** [comment]
It is no matter what the slider is on

**Comment by outphase** [comment]
Fix: Settings, General, Accessibility, Increase Contrast, Turn off Reduce White Point.

**Comment by anthonya1999** [comment]
@outphase Ah, yes if you have that on, the app won't work.

**Comment by deemidroll** [comment]
Thank you! It works correctly now.

**Comment by anthonya1999** [comment]
Awesome, thanks!
