### ISSUE TITLE
Reduce white point

### ISSUE THREAD

**Issue by DotTheI** [anthonya1999/GoodNight#2]
The application doesn'r work properly with the Reduce white point option enabled

**Comment by anthonya1999** [comment]
This is unfortunately something that can only be fixed through iOS, and not controlled by the app. Sorry!

**Comment by DotTheI** [comment]
This is definitely taken care by f.lux, which doesn't have that issue

**Comment by anthonya1999** [comment]
They have a little more flexibility, in regards to what they can do. Since their application is jailbreak-only, I assume they can modify some more things that we are just unable to.

**Comment by DotTheI** [comment]
@anthonya1999 No, they simply disable the option when the application starts
