### ISSUE TITLE
Can complete build

### ISSUE THREAD

**Issue by awests** [anthonya1999/GoodNight#22]
I cannot seem to complete a build for the project without getting the error: Embedded binary's bundle identifier is not prefixed with the parent app's bundle identifier.

**Comment by mariokorte** [comment]
Did you try a clean before build? 
Did you possibly forget to edit one of the identifiers (if you changed any of them)? There identifiers for the App, for the Widget and in the entitlements of those two products.

**Comment by anthonya1999** [comment]
You must the middle portion of both bundle IDs to something different.
