### ISSUE TITLE
Updates

### ISSUE THREAD

**Issue by fabdub** [anthonya1999/GoodNight#23]
Awesome app,
Is it possible to add in-app updates likes f.lux implemented when they shared their app ?

Thanks

**Comment by anthonya1999** [comment]
Unfortunately I can't do this only because for updates, you must redownload the source. I cannot release any compiled binaries of the app. This was a great idea though!

**Comment by mariokorte** [comment]
Well, even f.lux didn't really do updates. They checkt with their webpage if a new version number was available and would remind the user to download the new version and install it via Xcode. So, just an info that the is something new, not a real update though.

**Comment by anthonya1999** [comment]
Interesting. I'm not a web developer but I'll see if I can come up with something. Thanks!
