### ISSUE TITLE
Can't disable brightness level 

### ISSUE THREAD

**Issue by sankids** [anthonya1999/GoodNight#24]
On iphone 6s ios 9.1

After enabling low brightness setting disable works only on the first try.

Other attempts the switch flips to disable but the screen stays dimmed (enabled), must hit reset brightness together with enabling the switch to get the display brightness back to normal. Happens both in app and also 3d touch.

The same goes for color setting, while temperature enable disable works fine in app and 3D touch

**Comment by mariokorte** [comment]
This will be fixed when the next PullRequest is accepted.
