### ISSUE TITLE
6500K Temperature is not displaying correctly

### ISSUE THREAD

**Issue by boomming** [anthonya1999/GoodNight#26]
When I activate GoodNight and put the temperature at 6500K, the screen is still noticeably tinted orange. Putting the temperature at 6500K when GoodNight is activated should look the same as when GoodNight is not activated at all, but it does not. Moreover, once I enable GoodNight, disabling it only makes the screen return to the '6500K' temperature that is still tinted orange, not the regular temperature without GoodNight. I have to restart my phone every time I wish to return the temperature to normal.

I am on an iPhone 5, iOS 9.1, non-jailbroken. If you need anymore information, feel free to ask.

**Comment by mariokorte** [comment]
I cannot reproduce that. Hm. 

I Did: 
- delete app, 
- reboot, 
- install app while making sure the check to not execute unnecessary changes to gammtaable is not active (comment line 162 in GammaController.m)
- set gamma slider to 6500K
- turn on via enable switch
-> no change to screen temperature

Maybe you have a corrupted gammatable.dat? Please delete app, reboot and then reinstall app.

**Comment by mariokorte** [comment]
I believe you do have a point there, @boomming. Noticed some slight off color 6500K mode as well. Will investigate that.

**Comment by mariokorte** [comment]
Issue is resolved and waiting for pull into master. Thanks for your patience.
