### ISSUE TITLE
Geolocation

### ISSUE THREAD

**Issue by DotTheI** [anthonya1999/GoodNight#3]
Geolocation and consequently sunrise and sunset times are not used

**Comment by anthonya1999** [comment]
Yes, I am already looking into a way to do this. Thanks!

**Comment by abdulkar-im** [comment]
There's a discussion on GammaThingy regarding implementing auto change based on location using solar.c.

**Comment by anthonya1999** [comment]
I may implement this soon if I can actually ensure that it will turn on at the actual sunrise/sunset time. It uses Background App Refresh right now, which is not optimal for this. I'm going to do some digging into the SpringBoard, SpringBoardServices frameworks to see if there's a way to wake the app at those times.

**Comment by cburman01** [comment]
@anthonya1999 Could you send notifications to wake the app up to check sunrise/sunset times?

**Comment by mariokorte** [comment]
I already have a branch built for myself using sunrise and sunset. If wanted I can add a pull request.

**Comment by anthonya1999** [comment]
@mariokorte If you could do that, I would appreciate it, as I am not focusing on this project a lot until I get my iPad Pro to fix that issue, as that is the most concerning thing at this point. Thanks for helping out!
