### ISSUE TITLE
Strange colors

### ISSUE THREAD

**Issue by gregor2210** [anthonya1999/GoodNight#31]
Hi

I managed to download Goodnight after reading through the different guides. There was a problem where  I had to change the name on the Bundle Identifier on BOTH Goodnight and Goodnight Widget. Now I got the app on my iPhone 6s, but there is another problem. whenever I change the temperature, brightness or color, I get a lot of strange colors I KNOW shouldn't be there.

When I tried to get screenshots of the weird behaviour, I noticed the pictures was completely normal, they didn't get affected, just the iPhone/screen. 
![img_0083](https://cloud.githubusercontent.com/assets/9884624/11637996/dcd78068-9d24-11e5-9517-abe8a63f4113.jpg)
![img_0084](https://cloud.githubusercontent.com/assets/9884624/11637999/dceb1254-9d24-11e5-828d-27b86862fdea.jpg)
![img_0085](https://cloud.githubusercontent.com/assets/9884624/11637998/dcead028-9d24-11e5-9dc1-ef034d6c505b.jpg)
![img_0086](https://cloud.githubusercontent.com/assets/9884624/11637997/dce8e8f8-9d24-11e5-86c1-7525af7f9231.jpg)

Here is a few pictures taken from another phone: 
![img_1269](https://cloud.githubusercontent.com/assets/9884624/11638177/c34358c4-9d25-11e5-8a47-943c2dca5435.jpg)
![img_1270](https://cloud.githubusercontent.com/assets/9884624/11638184/c8f3173c-9d25-11e5-99d0-759d50af633d.jpg)
![img_1271](https://cloud.githubusercontent.com/assets/9884624/11638185/c908c348-9d25-11e5-9fc6-83fc3659de43.jpg)
![img_1272](https://cloud.githubusercontent.com/assets/9884624/11638186/c90906f0-9d25-11e5-94a6-d9bda0564c8e.jpg)

Please help me, I really want the app to work properly. I use an Iphone 6s 64gb Space gray not jailbroken

**Comment by rolyreyes** [comment]
Turn off "Reduce White Point".

**Comment by anthonya1999** [comment]
@rolyreyes Correct...just do that and it should be fine.
