### ISSUE TITLE
Blank Screen

### ISSUE THREAD

**Issue by lowercase28** [anthonya1999/GoodNight#37]
Went through entire process in Xcode, says that build was successful, then says running GoodNight on my iPhone, but when app opens it is only a black screen. What did I do wrong?

**Comment by anthonya1999** [comment]
Could you post a screenshot? Of Xcode and your phone? Thanks!

**Comment by lowercase28** [comment]
![screen shot 2015-12-12 at 9 31 34 pm](https://cloud.githubusercontent.com/assets/16272639/11765112/2f081842-a118-11e5-9a77-0f73cf677d6f.png)
This is the window that automatically opens on Xcode once the build is completed. The other screenshot is what automatically opens on my phone when I try to open GoodNight
![unnamed](https://cloud.githubusercontent.com/assets/16272639/11765130/89b6b898-a118-11e5-8de1-b76104cbbf48.png)

**Comment by mariokorte** [comment]
Please let us see more of the output text from the lower right sub-view in Xcode. Copy it here. What device are you using? What iOS Version?

**Comment by lowercase28** [comment]
2015-12-12 21:30:50.968 GoodNight[5424:60b] -[UIApplication registerUserNotificationSettings:]: unrecognized selector sent to instance 0x16d549f0
2015-12-12 21:30:50.975 GoodNight[5424:60b] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[UIApplication registerUserNotificationSettings:]: unrecognized selector sent to instance 0x16d549f0'
*** First throw call stack:
(0x2f23ef83 0x399efccf 0x2f242917 0x2f241203 0x2f190768 0xc49c1 0xc43ff 0x31acb587 0x31acaedb 0x31ac556b 0x31a616e9 0x31a60851 0x31ac4ca9 0x34079aed 0x340796d7 0x2f209a67 0x2f209a03 0x2f2081d7 0x2f172ebf 0x2f172ca3 0x31ac3ed1 0x31abf14d 0xc9215 0x39efcab7)
libc++abi.dylib: terminating with uncaught exception of type NSException

Using an iPhone 4 running iOS 7.1.2
(lldb)

**Comment by mariokorte** [comment]
Should be ok when current pull request is accepted into master.
