### ISSUE TITLE
Ability to select temperature per mode (normal vs change at time vs night mode)

### ISSUE THREAD

**Issue by shad0whawk** [anthonya1999/GoodNight#42]
This is more of a request than an issue but didn't know where to put it. 

First off, I love this app and appreciate all of the hard work and effort you guys are putting into it. I wanted to know if it's possible to add functionality to independently set the temperature per mode. I normally keep my daytime screen temperature at 5000K. In the evening, I'd like automatically change to 3400K at a specific time.  Then a bit later I'd like it to change to night mode at a desired time. Right now I have to do some of these manually. 

Does that make sense?

**Comment by mariokorte** [comment]
Good idea, I will do this in the near future. I already have an idea how to support it in GUI without adding to much clutter.

**Comment by shad0whawk** [comment]
Wow that was fast! Thank you! I have two observations I wanted to share. The slider control seems finicky when trying to adjust it on iOS 9.2 6S+. It doesn't seem very smooth and it's hard to get a specific value. Also the numbers get really blurry when adjusting which is purely cosmetic.
