### ISSUE TITLE
New Day/Night/Bedtime Modes not Working Right

### ISSUE THREAD

**Issue by shad0whawk** [anthonya1999/GoodNight#45]
I was playing around with the new modes functionality and I don't think it's working right (or I don't understand how it's suppose to work). If I enable the temperature, it defaults to 3400K (my night setting) -- no other toggles are on. It appears that the night toggle is the master setting for when the temperature setting is enabled. If I turn it off it goes back to 6500K. I tried enabling the time settings only and they work great for night mode and bedtime mode but day mode (the time prior to switching to night mode) still defaults to 6500K instead of my day setting of 5000K.  

Here's what I'm trying to do:  set my default temp to 5000K (which activates when I enable the switch to change to night mode at a specific time or simply by enabling the temperature switch), enable night mode based on time to activate at 7 pm at a temp of 3400K, and enable bedtime mode based on time to activate at 11 pm at a temp of 2000.

**Comment by shad0whawk** [comment]
Well maybe I was doing something wrong but I thinks it's working now.  One suggestion, if you enable the manual temperature switch at the top, replace the day/night/bedtime slider box with another slider object with a single option or somehow make it easy to identify which of the three controls is aligned with the manual setting.

**Comment by shad0whawk** [comment]
Also I think the manual control temperature setting should be independent of the three automatic mode controls so you can leave those set at specific settings for when you choose to enable it. Sometimes I like to toggle between manual and automatic mode but then I have to readjust the night mode setting because it's shared between the two.

**Comment by mariokorte** [comment]
They work as intended. The manual enabled mode (via the enabled switch) always uses the night temperature (or disables tinting completely when turned off). 
Only the automatic modes switch from day to night to bedtime modes automatically.

I will add a lock to the switcher when manual mode is enabled to remove this confusion.

**Comment by mariokorte** [comment]
Should be resolved when pull request #46 is accepted into master.
