### ISSUE TITLE
Feature request: A more compact widget

### ISSUE THREAD

**Issue by eyv** [anthonya1999/GoodNight#49]
Hi all,
This is a fantastic piece of work, and I want to thank everyone who contributed!

I have one small feature request: it seems that currently the widget occupies way more screen real estate than it needs. The text is carried over to two lines instead of one (it may fit on one for larger-screen devices). Also, the text is possibly not needed, since the button names are completely self-explanatory. I prefer my widgets as compact as possible, and this is no exception :) I tried to modify it myself, but have so little iOS development experience that even something as simple as attempting to remove the text caused a huge visual mess.

Thanks again everyone,
Eugene

**Comment by anthonya1999** [comment]
@eyv Thanks, I appreciate the kind words! The reason I made the widget that specific way (2 lines of text, button spacing, etc.) is because of the different screen sizes, so it would fit nicely despite all the various screen sizes of the iOS devices. I suppose I can remove the text, but I'll have to come up with something pretty creative for the other stuff. And constraints for NC widgets are awful, tbh :(

**Comment by eyv** [comment]
I understand. Didn't realize it would be so difficult. I am nothing if not patient. Hopefully you or someone else will decide to undertake this at some point. Thanks again for the great work!

**Comment by anthonya1999** [comment]
@eyv Oh, believe me, it was very bothersome to have it that way, especially since I'm using a 6+ myself. I do plan to keep trying to find a way to fix this. I'll leave this issue open for the time being. Thanks!

**Comment by mariokorte** [comment]
I am currently working on the widget anyway. Will work on that as well... Please a little patience.

**Comment by eyv** [comment]
Certainly. Thanks all!

**Comment by mariokorte** [comment]
Got a first working version in my widgetBranch: https://github.com/mariokorte/GoodNight/tree/groupsWidget

It would be nice if someone could test this prior to creating the pull request. Please make sure you replace all occurrences of "de.mariokorte1" with "your.own.id" (there are a few more now due to the use of app groups).

Please check the use of widget in combination with automatic modes; the widget overrides the auto updates until the next cycle:
- So if you enable gamma with the widget while auto is in day mode it will keep gamma enabled until auto will turn to day the next morning.
- If you enable gamma and after that disable gamma with the widget, both during daytime, it will keep gamma deactivated until the next day sunset.
- If you disable gamma with the widget while auto is in night mode it will keep gamma disables until auto will turn to day the next evening.
- If you disable gamma and after that enable gamma with the widget, both during night time, it will keep gamma activated the complete next day until it reaches sunrise again.

Any info is welcome on this matter. If this is found to be a good solution I will create the pull request.

**Comment by eyv** [comment]
I can try to test tonight. Just a clarification -- what happenings if location-based evening automation + time-based night automation is set rather than pure time-based evening automation?

**Comment by mariokorte** [comment]
Bedtime mode will only be activated if at that time the screen has active gamma. Else the bedtime mode will be skipped.

**Comment by eyv** [comment]
Thanks. A very stupid question: how do I pull and build THAT SPECIFIC BRANCH? I keep pulling the master. I'm not up on my git branching :( Thanks!

**Comment by eyv** [comment]
StackOverflow FTW: git clone <url> --branch <branch> --single-branch [<folder>] (https://stackoverflow.com/questions/1778088/how-to-clone-a-single-branch-in-git)

**Comment by mariokorte** [comment]
Or just use download as zip if you just want to try it out.

**Comment by eyv** [comment]
A procedural question: is this thread the correct place to discuss bug reports for that branch, or should I create new issues within your GitHub, @mariokorte?

OK, built and running.

One immediate bug report: when changing settings, the widget (and sometimes the status of GoodNight) doesn't auto-update. When selecting "Darkroom", darkroom doesn't actually engage (or disengage) until you press the button again. The worst part is, it doesn't happen EVERY time, just about 75% of the time. Sometimes it simply goes blank, and other times the button labels don't change after pressing them. You have to basically dismiss the Today view and pull it down again to get the widget to refresh, or push the buttons repeatedly. Sometimes after changing the widget state, the widget changes to "Unable to load". I've been fixing this by removing it from the Today view and re-adding. So, in short, the widget itself acts flaky. Will keep testing.

A second thing: when the Today pane refreshes, possibly by another app modifying the status of its own widget, the horizontal spacing between buttons in the GoodNight widget changes slightly. Barely noticeable but odd.

A third (cosmetic) thing: there's still a bit too much empty space between the color temperature text and the bottom of the widget.

Thanks again!

**Comment by mariokorte** [comment]
You can do as you like, but all bugs in just one thread can get difficult to track.

I don't have those issues that lot, but I will investigate why sometimes the widget is not responsive.

**Comment by mariokorte** [comment]
@eyv Did already try a little change to refresh the widget. Could you please test this?

**Comment by eyv** [comment]
@mariokorte , the problems are better in that they are completely consistent now. "Darkroom on" turns darkroom on. Tapping it the second time makes the icon teal, but doesn't actually turn off darkroom. Tapping it the third time turns off darkroom but half the time changes the widget to "Unable to load". Tapping the widget again loads it just fine.
Pressing "Gamma on" highlights that button and displays a color temperature of 3400K. That is neither the correct current color temperature of the screen nor is it any of my presets :) Tapping "Gamma off" returns the displayed color to the correct 6500K, but half the time changes the widget to "Unable to load". Tapping the widget again loads it just fine.

I hope this is helping. Thanks again for your hard work!

**Comment by eyv** [comment]
For some reason, GoodNight did not activate as scheduled. The displayed color temperature is wrong in the app.

**Comment by mariokorte** [comment]
This sounds like app groups is not correctly configured with your install:

1.) In the following files you need to change the id to 'group.xyz.id.goodnight'
GoodNight Widget.entitlements
GoodNight.entitlements
PrefixHeader.pch

2.) In Goodnight project you need to edit the id for the App and for the Widget to:
xyz.id.goodnight
xyz.id.goodnight.GoodNight-Widget

3.) Check for both under project -> GoodNight/GoodNight Widget -> Capabilities -> App Groups that the correct group (from 1.)) is listed, selected and not red (else push the "Fix it" button below that).

**Comment by eyv** [comment]
Ah, looks like I missed PrefixHeader.pch
Trying again...

**Comment by eyv** [comment]
OK, after fixing PrefixHeader, all seems to be well. There are still, however, a bunch of visual issues in the widget. The buttons move around. The color string does as well. Also, the color string does not refresh in real time. You have to dismiss the Today screen and get it back again to see the change as the screen slowly becomes more orange triggered by location.

**Comment by mariokorte** [comment]
I wil have a look into this erratic visual behavior. As long as the rest seem to be ok, this is a minor issue ;)

**Comment by eyv** [comment]
Well, SEEMS OK :) I haven't had a chance to test all the enable/disable combinations. But visuals are definitely weird. Like a haunted house :) Buttons move. Temperature doesn't refresh. Sometimes there's extra space at the bottom of the widget, and sometimes not.
But hey, it's progress. Thanks again!!

**Comment by eyv** [comment]
Another issue: after the screen is in bedtime mode (2000K), if I turn gamma off and then on again, it goes to night mode (3400K). If I then turn darkroom on and off, it once again returns to bedtime mode (2000K), just like I would have expected when originally toggling gamma off then on. Sorry, I've had a long day; did that make any sense?

**Comment by mariokorte** [comment]
Yes, did understand that. Works like intended, I would say:

Toggle Gamma Button toggles between night-mode gamma and off (when automatic mode is enabled this will be again restored in the next cycle). 
The darkroom button turns on darkroom mode and on deactivation of darkroom mode resumes to automatic mode immediately.

**Comment by eyv** [comment]
Excellent. Then other than the visual issues, I can't find anything else wrong.

**Comment by anthonya1999** [comment]
@eyv So can this be closed, or would you like to wait until @mariokorte creates the widget update?

**Comment by mariokorte** [comment]
@anthonya1999 let's keep this open until I fix the visual issues and push the changes to master.
