### ISSUE TITLE
Automatic Temperature Changing Not Working

### ISSUE THREAD

**Issue by pauloruberto** [anthonya1999/GoodNight#5]
Even though it is enabled, it does not change at 7pm & 7am.

**Comment by anthonya1999** [comment]
It will not change at exactly 7pm or 7am, (or whatever time you set it to). It uses background app refresh to keep checking every 15 minutes. It may check, say, at 7:12pm for example. Also, this feature is a little whacky sometimes, it doesn't work 100%. The commits that have been made are just slowly implementing this feature.

**Comment by Romeo0119** [comment]
Does this impact battery life at all to have this runs in the background and check the time every 15 mins?

**Comment by anthonya1999** [comment]
It shouldn't really, a lot of apps have this functionality, so it shouldn't impact it too much, it;'s just another app that uses it.

**Comment by bryandmlee** [comment]
Hi Anthony, I'm facing an issue related to this. I understand that BAR may not kick in at the selected time, but it seems that even when I manually open the app after the time change, the auto-switching doesn't do it's thing either. I've also tried quitting the app and re-opening, but it still remains in the previous state (especially when going from Enabled to Disabled). Furthermore, even manually turning Automatic Color Changing off and on in the app (after the set 7am) won't switch Temperature Enabled off.

(For now, I'm falling back on the workaround of using 3D Touch when evening comes/I wake up in the morning.)

**Comment by Xaositek** [comment]
I am running into this also - no amount of ensuring the app is running seems to get it to auto change. I've even left the phone unlocked, opened the app at 4:59pm (my enable time is 5:00pm) and then jumped back to the home screen. Auto-lock is turned off and at 5:20pm it still had not automatically changed.

**Comment by anthonya1999** [comment]
I am aware of this issue. When I added the Kelvin scale, something happened with this feature that caused it to be enabled and immediately disabled. So you couldn't tell if it was trying to turn on or not. I'll look into this more. Thanks

**Comment by anthonya1999** [comment]
This should be fixed with the latest pull request.
