### ISSUE TITLE
Latest Build not Working Right

### ISSUE THREAD

**Issue by shad0whawk** [anthonya1999/GoodNight#51]
As of commit 25aec5dxx, the temperature isn't working right in my 6s+ on 9.2. Using manual mode, the temperature initially displays correctly at 6500K. If I adjust it and try to get it back to 6500K it doesn't show correctly. The 6500K value has a pinkish tint to it. As soon as I move the slider even slightly the screen immediately get too much pink/orange to it. Also, all of the other values have more orange to them than they should. Sometimes when I disable the manual setting the screen doesn't revert back to the true 6500K value. I have to flip the toggle a few times and slide the slider around and finally it reverts back to the true 6500K value.

**Comment by mariokorte** [comment]
Will be fixed when pull request #52 is pulled into master.
