### ISSUE TITLE
iPhone 6 maintaining orange hue after disabling temperature change.

### ISSUE THREAD

**Issue by joshuacole** [anthonya1999/GoodNight#55]
I have auto change temperature activated (night mode as well) and in the morning after the app has reverted, there's still an orange-ish hue to the color of the device. If I restart it changes back to its correct color. My iPad Air 2 doesn't seem to do that.

**Comment by mariokorte** [comment]
Do you use the latest version? This bug should have been squashed in a previous commit.

**Comment by joshuacole** [comment]
I thought I was - I just reinstalled and I’ll check in after the day has switched back automatically.

**Comment by anthonya1999** [comment]
@joshuacole Any news on this?

**Comment by meetdesai** [comment]
does it works with iphone 5 and ipad 2 can you put compatibilty list thank you in advance

**Comment by meetdesai** [comment]
how do i make it work on my apple watch ?

**Comment by joshuacole** [comment]
It appears to have worked. I deleted the old app on my device and used the most recent version.
