### ISSUE TITLE
Need version / branch number... somewhere

### ISSUE THREAD

**Issue by eyv** [anthonya1999/GoodNight#56]
Hi all,

Right now, I have no earthly idea which version/branch/build I'm running, and it doesn't seem I can find out from the app. There should probably be a branch / commit / version number or something available inside the app, yes?

Thanks!

**Comment by anthonya1999** [comment]
@eyv Well, what i would suggest here would be to turn on notifications for the repo, or "watch" the project. Putting commits in the app via versions/build numbers is very unconventional.

**Comment by eyv** [comment]
Already watching :)

**Comment by anthonya1999** [comment]
@eyv Awesome, thanks! I'll try to think of some way to do something along these lines...
