### ISSUE TITLE
Wrong timing

### ISSUE THREAD

**Issue by DotTheI** [anthonya1999/GoodNight#6]
The application doesn't stop working at 7AM. I've been using it fro two days now and the screen is still yellow at 7AM. Haven't noticed though when it changes hue back to normal though. I am using iOS 9.0.2 on an iPhone7,2 device.

**Comment by anthonya1999** [comment]
Yeah, it uses background app refresh to see if it's time to turn it on or off, and since it checks every 15 minutes, it doesn't turn on at *exactly* 7am or 7pm, but whenever iOS decides to wake up the app.

**Comment by mariokorte** [comment]
The backgroundFetch approach is quite random in execution as iOS picks the update times as it pleases (the setMinimumBackgroundFetchInterval is just the minimum time period of execution.)
I added a pull request to at least set this value to 10 minutes regularly by using the VOIP keep alive timer.
