### ISSUE TITLE
Add Apple TV support

### ISSUE THREAD

**Issue by PannenkoekenNL** [anthonya1999/GoodNight#61]
Could you add support for the 4th generation Apple TV?

**Comment by anthonya1999** [comment]
@PannenkoekenNL It's very possible, it has the same frameworks as the iPhone, so in theory it should already work. Will look into it...

**Comment by anthonya1999** [comment]
This may be possible by changing the gamut matrix. I just remembered I actually tried it using the gamma table in the past, but it wouldn't allow me to do so, it had something to do with the gamma table file in the documents folder

**Comment by anthonya1999** [comment]
Looked into it, but IOMobileFramebufferGetMainDisplay actually fails right off the bat, so we can't really do anything about that, since the framebuffer connection will be NULL.
