### ISSUE TITLE
New Build Issue

### ISSUE THREAD

**Issue by shad0whawk** [anthonya1999/GoodNight#62]
A few widget observations.  Using "Gamma On" doesn't seem to play nicely with using the color changing time setting.  If have Color Changing (Time) enable, enabling Gamma On changes it to 3400K overriding the daytime setting (5000K) I have specified.  Disabling Gamma On/Off, returns the screen to 6500K instead of the original 5000K but leaves the Color Changing (Time) button enabled.  The screen doesn't revert to the correct temperature until I disable/reenable the time based setting.

Also, if I turn Gamma On in the widget, then enable Darkroom On in the widget, the screen becomes a greyscale of sorts (sometimes). If I enable Darkroom On, then enable Gamma On, gamma comes on but the darkroom toggle doesn't revert to darkroom on.  If I enable Gamma On and then disable it, then enable Darkroom on, the screen also goes to greyscale.  This is on an iPhone 6.

**Comment by anthonya1999** [comment]
@mariokorte Would you mind taking a look at this? Cause you mostly made the widget, and I haven't had time to look at it yet...thanks!

**Comment by mariokorte** [comment]
Part of this (the first one to be more specific) is intentional. Will come back to this and explain this in a few minutes... The other issues will be removed of course.

**Comment by mariokorte** [comment]
The widget's gamma toggle button just toggles between night gamma and gamma off (like the enable button in the temperature part of the app). It overrides the auto updates until the next cycle:

So if you enable gamma with the widget while auto is in day mode it will keep gamma enabled until auto will turn to day the next morning.
If you enable gamma and after that disable gamma with the widget, both during daytime, it will keep gamma deactivated until the next day sunset.
If you disable gamma with the widget while auto is in night mode it will keep gamma disables until auto will turn to day the next evening.
If you disable gamma and after that enable gamma with the widget, both during night time, it will keep gamma activated the complete next day until it reaches sunrise again.

Bedtime mode will only be activated if at that time the screen has active gamma. Else the bedtime mode will be skipped.

The darkroom button turns on darkroom mode and on deactivation of darkroom mode resumes to automatic mode immediately.

Any better ideas are welcome.

**Comment by mariokorte** [comment]
The bugs you mentioned should be squashed by commit 5fb676d2e9c9b7ec6892a2bbeb5271b923ec011e the other thing is not a bug, but a feature ;)

If you have ideas for better solutions please open an enhancement issue. Thank you!

**Comment by shad0whawk** [comment]
One more thing that's changed that may be a bug.  In the version prior to the widget enhancements, if I have the color time change enabled, then I turn on dark mode within the app and subsequently turn it off, the screen would revert back to the temperature settings it was previously using (5000K assuming it's daytime).  Now after turn off dark mode in the app, the former color time change settings are not enforced (reverts to 6500K) assuming daytime) but they are still enabled within the temperature screen.  FYI this has nothing to do with any adjustment I've made in the widget because I haven't looked at that yet.

**Comment by mariokorte** [comment]
OK, will look into that as well. Thanks for finding the issue ;)

**Comment by shad0whawk** [comment]
Sorry just trying to be helpful.  I do love the app and use it every day so please keep up the good work!

**Comment by mariokorte** [comment]
No need to be sorry!

**Comment by shad0whawk** [comment]
The widget toggles seem to work as expected now.  The UI elements update and no more greyscale shades.

**Comment by shad0whawk** [comment]
As for an enhancement to these controls, because I use the automatic time changing and have my daytime set to 5000K, I would like to see the program retain and revert to the prior settings after disabling Gamma On and Darkmode On if that's possible.  It seemed to work that way previously with the darkroom mode within the app.

**Comment by mariokorte** [comment]
I think you are speaking about the widget function? I came up with this solution instead toggling between night and day gamma because otherwise you are not able to deactivate gamma completely. But sometimes it is necessary to do this (for example if you want to check on some pictures with the colors right). Maybe I think of a tristate solution (night -> day -> off -> night -> ...) What do you think?

**Comment by shad0whawk** [comment]
I think that'll probably work.  I'll try it out when it's available.

**Comment by shad0whawk** [comment]
I think you already answered my last questions in the previous post.  Please disregard those.

**Comment by shad0whawk** [comment]
Thanks for pushing out these updates.  It works great!
