### ISSUE TITLE
iOS compatitbilty

### ISSUE THREAD

**Issue by HaginCodes** [anthonya1999/GoodNight#64]
is this tweak compatible with iOS 7? if not could you please make it so? i would be willing to help in order to make this possible

**Comment by mariokorte** [comment]
Should be compatible with ios7 as is. If it's not you should file a bug report with explanation how the crash occurs.

**Comment by HaginCodes** [comment]
yes i installed it and when i disconnected it and tried to change some of the toggle settings and the app keeps crashing

**Comment by mariokorte** [comment]
Please read this and check your configuration!

https://github.com/anthonya1999/GoodNight/issues/63

**Comment by HaginCodes** [comment]
ok the app works now for the most part and i followed IcU's tutorial online but the darkroom toggle and the brightness toggle don't work the app crashes, but other wise everything else is fine, although it would be nice to have it working on my phone because i use it on my computer. How do i fix this

**Comment by mariokorte** [comment]
What iOS version are you using? What devices? Could you run the version from xcode and when it crashes give me the output from the sub-window in the lower right corner? (If the console is not visible go to "View -> Debug Area -> Activate Console" or hit "Shift+Cmd+C")

**Comment by HaginCodes** [comment]
im on an iphone 4 running ios 7.1.2

**Comment by HaginCodes** [comment]
what do i copy and paste when the error occurs do i give you the line that is highlighted?

**Comment by mariokorte** [comment]
Just everything from the output (console) window will suffice.
The highlighted line is part of the editor window. Enter the previously mentioned shortcut on the keyboard to show the console window in the lower right corner of the window.

**Comment by mariokorte** [comment]
@HaginCodes Is this still a problem? Otherwise this will be closed within the next 24hrs.

**Comment by HaginCodes** [comment]
2015-12-29 09:18:54.822 GoodNight[1002:60b] *** Assertion failure in -[IOMobileFramebufferClient callFramebufferFunction:withFirstParamScalar:], /Users/hagin/Downloads/GoodNight-f6f3ada1990594042930282a7f8709dba495fffd/GoodNight/IOMobileFramebufferClient.m:70
2015-12-29 09:18:54.830 GoodNight[1002:60b] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Invalid parameter not satisfying: IOMobileFramebufferFunction'
*** First throw call stack:
(0x2e56af83 0x38d1bccf 0x2e56ae5d 0x2ef18d5b 0x9c591 0x9c85d 0xb74c9 0xb7547 0xaa9b1 0x30dbd037 0x30dbcfd7 0x30dbcfb1 0x30da8717 0x30ff3eef 0x30ff3a7f 0x30f0dfed 0x30db94e3 0x31160aed 0x30d80353 0x30d7ea9b 0x30db7d49 0x30db766f 0x30d8c8cd 0x30d8af77 0x2e53620b 0x2e5356db 0x2e533ecf 0x2e49eebf 0x2e49eca3 0x333a4663 0x30deb14d 0xb59a1 0x39228ab7)
libc++abi.dylib: terminating with uncaught exception of type NSException
(lldb) 



thats the error i get, also it doesn't use location services and it says that i enable it in settings but there is nothing there about location services.

**Comment by mariokorte** [comment]
@HaginCodes Should be fixed now. Please update your code and report back.

**Comment by HaginCodes** [comment]
Thank you I'll check it out later today, I'm out with family right now.

**Comment by HaginCodes** [comment]
where do i paste the code so that it doesn't mess up

**Comment by mariokorte** [comment]
Don't paste a patch, just pull latest version from the repository (or download a new zip).

**Comment by HaginCodes** [comment]
ok so the one in your repo?

**Comment by HaginCodes** [comment]
hey just updated and it works :100:  thank you :+1:
