### ISSUE TITLE
Force Close after using newest Version?

### ISSUE THREAD

**Issue by samluxh** [anthonya1999/GoodNight#68]
Hi,

the app force closes if I want to activate one of the 4 Adjustments.
It was working fine the last days. I have updated the source and now it force closes. I discarded all changes in Xcode and deleted the app and used git pull, but it still crashes :/

Can I get the old version (maybe 2 days ago)?

Thanks in advance!

**Comment by hbarn** [comment]
I am experiencing the same issue and came to report it as well.

Turning any of the adjustments on or off (except for White Point when no other adjustments are enabled) causes a crash in recent changes.

Running latest iOS 9.2 13C75.

I have attached crash reports below:

[GoodNight_2015-12-29-223940_Haydens-iPhone.crash.txt](https://github.com/anthonya1999/GoodNight/files/74566/GoodNight_2015-12-29-223940_Haydens-iPhone.crash.txt)
[GoodNight_2015-12-29-224112_Haydens-iPhone.crash.txt](https://github.com/anthonya1999/GoodNight/files/74567/GoodNight_2015-12-29-224112_Haydens-iPhone.crash.txt)
[GoodNight_2015-12-29-224117_Haydens-iPhone.crash.txt](https://github.com/anthonya1999/GoodNight/files/74568/GoodNight_2015-12-29-224117_Haydens-iPhone.crash.txt)
[GoodNight_2015-12-29-224123_Haydens-iPhone.crash.txt](https://github.com/anthonya1999/GoodNight/files/74569/GoodNight_2015-12-29-224123_Haydens-iPhone.crash.txt)
[GoodNight_2015-12-29-224127_Haydens-iPhone.crash.txt](https://github.com/anthonya1999/GoodNight/files/74570/GoodNight_2015-12-29-224127_Haydens-iPhone.crash.txt)
[GoodNight_2015-12-29-224134_Haydens-iPhone.crash.txt](https://github.com/anthonya1999/GoodNight/files/74571/GoodNight_2015-12-29-224134_Haydens-iPhone.crash.txt)
[GoodNight_2015-12-29-224138_Haydens-iPhone.crash.txt](https://github.com/anthonya1999/GoodNight/files/74572/GoodNight_2015-12-29-224138_Haydens-iPhone.crash.txt)
[GoodNight_2015-12-29-224142_Haydens-iPhone.crash.txt](https://github.com/anthonya1999/GoodNight/files/74573/GoodNight_2015-12-29-224142_Haydens-iPhone.crash.txt)
[GoodNight_2015-12-29-224206_Haydens-iPhone.crash.txt](https://github.com/anthonya1999/GoodNight/files/74574/GoodNight_2015-12-29-224206_Haydens-iPhone.crash.txt)
[GoodNight_2015-12-29-224210_Haydens-iPhone.crash.txt](https://github.com/anthonya1999/GoodNight/files/74575/GoodNight_2015-12-29-224210_Haydens-iPhone.crash.txt)
[GoodNight_2015-12-29-224216_Haydens-iPhone.crash.txt](https://github.com/anthonya1999/GoodNight/files/74576/GoodNight_2015-12-29-224216_Haydens-iPhone.crash.txt)
[GoodNight_2015-12-29-224222_Haydens-iPhone.crash.txt](https://github.com/anthonya1999/GoodNight/files/74577/GoodNight_2015-12-29-224222_Haydens-iPhone.crash.txt)
[GoodNight_2015-12-29-224106_Haydens-iPhone.crash.txt](https://github.com/anthonya1999/GoodNight/files/74565/GoodNight_2015-12-29-224106_Haydens-iPhone.crash.txt)

**Comment by mariokorte** [comment]
What iOS version are you using? What devices? 
Could you run the version from xcode and when it crashes give me the output from the console window in the lower right corner? (If the console is not visible go to "View -> Debug Area -> Activate Console" or hit "Shift+Cmd+C"), plus tell me what exactly you did when this crash occurred.

**Comment by samluxh** [comment]
iPhone 6S on iOS 9.2

After app started, I tapped on Temperature and then on Enabled to enable it and then it crashed (force close).

Console Output:
2015-12-30 13:47:42.998 GoodNight[2659:958404] *** Assertion failure in +[GammaController setGammaWithTableAndRed:green:blue:], /Users/hi/Documents/GoodNight/GoodNight/GammaController.m:130
2015-12-30 13:47:42.999 GoodNight[2659:958404] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Invalid parameter not satisfying: file != NULL'
*** First throw call stack:
(0x181d85900 0x1813f3f80 0x181d857d0 0x1826f899c 0x10006dda8 0x10006d5b8 0x10006e29c 0x10006facc 0x18272c334 0x18267f100 0x18266f348 0x18272e728 0x1000e1bb0 0x1000ee6c8 0x1000e58a0 0x1000f07e0 0x1000f04d8 0x1819ed470 0x1819ed020)
libc++abi.dylib: terminating with uncaught exception of type NSException
(lldb)

**Comment by mariokorte** [comment]
@samluxh This is the same error as in https://github.com/anthonya1999/GoodNight/issues/63 . Please check, that all IDs (BundleIdentifier for App and Widget as well as all references to AppGroup IDs) are set up correctly!

**Comment by samluxh** [comment]
It is working now, thank you. I had to change App Groups.
Steps 8-13 in https://github.com/anthonya1999/GoodNight/blob/master/Help/README.md

Can be closed :)
