### ISSUE TITLE
Unable to build

### ISSUE THREAD

**Issue by pH14** [anthonya1999/GoodNight#7]
This is probably an issue on my end, but I'm trying to build GoodNight without any changes and I'm getting the following errors: https://gist.github.com/pH14/4a234d79ddd4ea9fa487

This is with Xcode 7 and Xcode 7-beta, any thoughts?

**Comment by anthonya1999** [comment]
Are you building for the simulator? If so, you must be on "Generic iOS Device" or your own device when building.

**Comment by pH14** [comment]
Same errors when building for my own device. Hmm... wonder what's up with my Xcode config, I haven't touched it since installing

**Comment by pH14** [comment]
Reinstalling Xcode worked, so, mystery solved? Thanks for the great app!
