### ISSUE TITLE
Assertion failure on 9.2.1 Public Beta 2

### ISSUE THREAD

**Issue by wzxu** [anthonya1999/GoodNight#76]
Whenever I move the slider to adjust temperature, in GammaController.m:130, an assertion failure happens:

```2016-01-08 08:09:07.564 GoodNight[317:79220] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Invalid parameter not satisfying: file != NULL'```

Seems like `fopen` fails?

**Comment by mariokorte** [comment]
Yes, because you did forget to update one of the IDs or not all of the IDs use the same prefix. Please double check!

**Comment by wzxu** [comment]
Oops! Should've checked the guide again after the widget was added. Forgot to update PrefixHeader.pch. Thanks.
