### ISSUE TITLE
Crash upon temperature change.

### ISSUE THREAD

**Issue by wasp604** [anthonya1999/GoodNight#77]
Did not occur on the version I got last week. And it still says version 1.1 for some reason in Xcode.

**Comment by mariokorte** [comment]
I need the output from the console in xcode please. But I guess it is due to misconfiguration...

**Comment by wasp604** [comment]
What happened was:
I downloaded a new version and deleted the old one. But the colour
temperature was incorrect because the old one was active when I deleted it.

I fixed the issue by reinstalling the old version.

I really don't want to mess with it now, but if it happens again when I try
to update it I'll get the output for you.

**Comment by mariokorte** [comment]
If that happens again just delete the version from the device, reboot and reinstall. Everything will be fine then.
