### ISSUE TITLE
iOS 9.2.1 beta 2 crash iPhone 6S+

### ISSUE THREAD

**Issue by nickh4xdawg** [anthonya1999/GoodNight#80]
When trying to move the temperature slider, it crashes the app. It also crashes when trying to turn the location option on and turning on the other switches. The app started crashing after updating to beta 2. It works fine on the iPad Pro on beta 2 though.

**Comment by shad0whawk** [comment]
I have a 6s+ running 9.2.1 Beta 2 and the app works fine--no crashes here.

**Comment by nickh4xdawg** [comment]
i dont know what kind of voodoo you have but i can't manage to get it to work at all. As soon as i updated it stopped working. I have a screen recording of it. I uninstalled and reinstalled multiple times and can't get it to work.

**Comment by shad0whawk** [comment]
Did you make all of the configuration changes including the app groups, *.pch file update, app name, registered developer?  I always clean out the old files/build in Xcode before I rebuild and install it.

**Comment by mariokorte** [comment]
Please check all IDs. Follow the instructions in the help folder!
