### ISSUE TITLE
As soon as you click Automatic Color Changing toogle the app crashes

### ISSUE THREAD

**Issue by leocrespo** [anthonya1999/GoodNight#81]
Iphone 6s Plus, as soon as you click the toogle the app crashes. It works fine with 3d touch. 

Shame because the schedule would be very useful.

**Comment by shad0whawk** [comment]
It works fine on my 6S+ on 9.2.1 Beta 2.

**Comment by shad0whawk** [comment]
I would delete the app from your phone, check all of your configuration settings, clean the cache in Xcode, and rebuild/reinstall.

**Comment by leocrespo** [comment]
That solved the problem, thank you. Plenty of new options now
