### ISSUE TITLE
Question on Functionality

### ISSUE THREAD

**Issue by shad0whawk** [anthonya1999/GoodNight#84]
This is more of a question than an issue.  I have the temperature controls enable--specifically using location option.  If I'm on the temperature screen and adjust the temperature setting for any of the modes (day/night/bedtime), the screen updates to reflect that temperature (which makes sense).  I would assume this would be temporary to show what that temperature looks like, but it never reverts back to the current set temperature until I close the app and reopen it or disable/enable the location-based setting.  Is this how it's supposed be.  I would like to see it show that temperature for maybe 5 seconds and then revert back to the current temperature based on either time or location.

**Comment by mariokorte** [comment]
Yes, you are right. This is a bug. Will fix this soon.
