### ISSUE TITLE
Can someone confirm (possible bug): GoodNight does not correctly adjust to time zone changes

### ISSUE THREAD

**Issue by eyv** [anthonya1999/GoodNight#87]
I just traveled to the east coast. While I can't confirm it, it didn't seem that GoodNight adjusted either the location-based fading or the time-based. Fading didn't seem to correspond to the sunset in my location; GoodNight was still doing its thing, but on central time, even though the phone auto-adjusted to east coast time.
Can anyone confirm whether GoodNight correctly reacts to time zone changes?

**Comment by mariokorte** [comment]
Cannot reproduce that problem. Changed timezones manually and GoodNight reacted as intended.
