### ISSUE TITLE
Crashes on iOS 9.3 Beta 1

### ISSUE THREAD

**Issue by vista980622** [anthonya1999/GoodNight#88]
![2016-01-17 12 34 45](https://cloud.githubusercontent.com/assets/6680542/12373377/23f1c790-bcb2-11e5-8061-b7f73bd18aad.png)

**Comment by Pukinator** [comment]
I have the exact same issue.
iPhone 6s 9.3 Public Beta

**Comment by mariokorte** [comment]
@Pukinator What you describe is not what I would call "having the exact same issue" as @vista980622 .

**Comment by mariokorte** [comment]
Cannot reproduce this. This app runs fine on my iOS 9.3 beta device.

**Comment by Pukinator** [comment]
Sorry for my choice of words. I meant that it crashes exactly like on the picture.
