### ISSUE TITLE
Crashes on every app opening after changing a setting

### ISSUE THREAD

**Issue by bistacos** [anthonya1999/GoodNight#89]
Unfortunately, I can't get any of the color temp changes working before the app starts crashing and then crashes immediately whenever I try to reopen it.

Lots of crashes when clicking "enable" on brightness or temperature.

iPhone 5 running iOS 9.2 (13C75)

**Comment by anthonya1999** [comment]
@bistacos Did you change the app group ID in the prefix header to match your app group ID located in the capabilities? Make sure to follow the setup process in the README.

**Comment by mariokorte** [comment]
I bet it is related to not correctly configures IDs. Please double check all places mentioned in the readme from the help-folder.

**Comment by bistacos** [comment]
I'll check it again tonight.  Thanks for checking up!

**Comment by bistacos** [comment]
@anthonya1999 @mariokorte : Issue was that appGroupID in PrefixHeader.pch defaulted to end in .GoodNight in my master copy--needed to be changed to .goodnight to run properly.  If I missed that somewhere in the instructions, my apologies.  Thanks for getting back to me quickly!
