### ISSUE TITLE
Crashes when compiled on Xcode 7.3 Beta

### ISSUE THREAD

**Issue by vista980622** [anthonya1999/GoodNight#90]
As it turns out, the crashing issue is unrelated to iOS 9.3 Beta. Instead, it is an issue only when compiled with Xcode 7.3 beta. Since the original report is closed, I have started a new one.

![2016-01-17 12 34 45](https://cloud.githubusercontent.com/assets/6680542/12373377/23f1c790-bcb2-11e5-8061-b7f73bd18aad.png)

Can anyone kindly look into this issue?

Thanks!

**Comment by Pukinator** [comment]
I also have this crashing issue, but it also crashes in Xcode 7.2. But it compiles perfectly if I download this: https://github.com/anthonya1999/GoodNight/tree/1eb3e6e26a382f2672f31a7a1a7c353468d59546 so maby it's related to some new code.

**Comment by mariokorte** [comment]
I can compile and run the latest code with all versions of Xcode. Of course Xcode 7.3beta is needed to run this on 9.3beta.
Also, @Pukinator , there have not been any big changes between the version you mentioned and current master.
This must be some kind of configuration error on your sides. Please check out fresh and make the changes mentioned in the help folder to try again.

**Comment by Pukinator** [comment]
Hmm Pretty weird, the master version also crashes on Simulator. I also reinstalled Xcode, still crashing. Really weird, maybe related to something else on my mac

**Comment by mariokorte** [comment]
@Pukinator This project can never run on simulator because it uses private APIs that are not available on simulator.

**Comment by jayfn** [comment]
I installed the Xcode 7.3beta to test it myself. On the iPhone 5 (9.3 public beta) the app is crashing as soon as you enable the temperature control.

Please see the attached picture
![bildschirmfoto 2016-01-21 um 21 10 15](https://cloud.githubusercontent.com/assets/16825088/12493034/8589d6bc-c083-11e5-9313-0730540e4c36.png)

**Comment by mariokorte** [comment]
And again for the millionth time the same error : wrong ids. Please check that you follow the steps from the help folder! Check that there are no typos in the ids!

Please check the closed issues as well next time There are at least 3 topics with this exact problem...
