### ISSUE TITLE
Bedtime Mode not activating in background

### ISSUE THREAD

**Issue by Noah-Scarbrough** [anthonya1999/GoodNight#91]
This app is great! The problem I am having though, is I have to enter the app for Bedtime Mode to enact. Is this not supposed to activate in the background, or is it a bug?

**Comment by mariokorte** [comment]
Should be activated in background when one of the other automatic modes is also active. You know, that when you select 23:00 (11pm) it can take up to 23:15 (11:15pm) to be activated tue to the fact that this app can take up to 15 minutes between updates in background?

You can see in the temperature view's footer below the automatic modes when it updated the last time in the background. Please check those times for further information.

**Comment by Noah-Scarbrough** [comment]
Yeah! That's what it was. I feel pretty stupid right about now. :D Thank you!
