### ISSUE TITLE
not working iphone 4s

### ISSUE THREAD

**Issue by Tealfish** [anthonya1999/GoodNight#94]
iPhone 4s ios 9.2

after following your guide to install GoodNight on my iPhone, it kept crashing... I re-ran it on my mac so it could debug as I ran. the line that errored out was
```swift
NSParameterAssert(file != NULL);
```
line 130 in GammaController.m
with the error text:
```
Thread 3: signal SIGABRT
```
so I commented off that entire block just to see what happened
from this
```swift
    if (file == NULL) {
        [[IOMobileFramebufferClient sharedInstance] gammaTable:&data];
        file = fopen([filePath UTF8String], "wb");
        NSParameterAssert(file != NULL);
        
        fwrite(&data, 1, sizeof(data), file);
        fclose(file);
        
        file = fopen([filePath UTF8String], "rb");
        NSParameterAssert(file != NULL);
    }
```
to this
```swift
//    if (file == NULL) {
//        [[IOMobileFramebufferClient sharedInstance] gammaTable:&data];
//        file = fopen([filePath UTF8String], "wb");
//        NSParameterAssert(file != NULL);
//        
//        fwrite(&data, 1, sizeof(data), file);
//        fclose(file);
//        
//        file = fopen([filePath UTF8String], "rb");
//        NSParameterAssert(file != NULL);
//    }
```
the next line that errored out was line 139 (same file) with
```swift
fread(&data, 1, sizeof(data), file);
```
but it gave me the error text
    Thread 5:EXC_BAD_ACCESS (code=1, address=0x38)
I'm not sure what all this means I'm just a ruby script kiddie
so any help would be appreciated as I hate all the blue light from my phone at night but apple won't support it on my phone (a real dick move, apple)
thx
Sam

**Comment by mariokorte** [comment]
You did not follow the instructions in the help directory: In detail: Check that all your IDs are changed correctly in all places and that there are no typos.
